### ISSUE TITLE
Issues loading configs on macOS

### ISSUE THREAD

**Issue by VinnyWr** [ModdingX/LibX#25]
===================Control Test===================
Created a new instance with Minecraft 1.16.5, Feywild, MythicBotany, and their dependencies

Launched with warnings and errors but no halt

Feywild title screen is shown as expected

Created New World in survival mode w/cheats

Changed game mode to creative

Gave myself the hammer

Changed back to survival and the hammer dropped as expected

Config setting is currently `"requirement": "effect",`

log for control test:
[latest.log](https://github.com/noeppi-noeppi/LibX/files/7220822/latest.log)
======================= ======================

+++++++++++++++++++Test After Config Changes+++++++++++++++++++
Changing feywild/client.json5 to `replace_menu: false,`

Changing mythicbotany.json5 to `"requirement": "nothing",`

Launched with warnings and errors but no halt

Feywild title screen is shown which goes against the config

Created New World in survival mode w/cheats

Changed game mode to creative

Gave myself the hammer

Changed back to survival and the hammer stayed in my hands as expected

Config setting is currently `"requirement": "nothing",`

Saved and quit to title to make sure the title screen did not update, it did not. See Snip:
![forGithub](https://user-images.githubusercontent.com/43010025/134586560-927d5a2a-de49-44b4-a2a6-6cec47d241ea.PNG)

log for config changes
[latest.log](https://github.com/noeppi-noeppi/LibX/files/7220902/latest.log)
++++++++++++++++++++++++++++++++++++++

It appears that only 'feywild:compat' is failing to load.

**Comment by noeppi-noeppi** [comment]
Some more information we already gathered: It seems to be a problem on macOS. It seems that the config is not detected to be existing and thus is created again with the default values.

It is a problem in 1.16. It has not yet been tested whether the same problem is present in 1.17

**Comment by noeppi-noeppi** [comment]
However the log and screenshot you sent here, show a malformed json. There is a comma too much after the last entry. Could you adjust that and upload the log again?

**Comment by VinnyWr** [comment]
All of my testing was done in a win10 environment. Either way removing that comma did the trick. Sorry for taking your time with something Das and I should've seen.
