### ISSUE TITLE
3.2.11 - Crash on startup.

### ISSUE THREAD

**Issue by lazynessmind** [ModdingX/LibX#53]
The game goes into a broken state while trying to startup. 

From what I have seen the problem was caused by this:
```
java.lang.IllegalAccessError: class io.github.noeppi_noeppi.libx.mod.registration.ModXRegistration tried to access private method 'boolean net.minecraft.resources.ResourceLocation.isValidPath(java.lang.String)' (io.github.noeppi_noeppi.libx.mod.registration.ModXRegistration is in module libx@1.18.2-3.2.11 of loader 'TRANSFORMER' @77774571; net.minecraft.resources.ResourceLocation is in module minecraft@1.18.2 of loader 'TRANSFORMER' @77774571)
```

[Log](https://github.com/noeppi-noeppi/LibX/files/8477420/2022-04-13-1.log)

**Comment by noeppi-noeppi** [comment]
In your log, it seems like the accesstransformer is not applied. However, I could not reproduce this when testing it myself in a LibX and Wooden Utilities development environment. The game started just fine.

**Comment by lazynessmind** [comment]
Did you check the LibX version being used? Modern has downgraded the version of LibX. https://github.com/ModernGamingWorlds-Mods/Wooden-Utilities/commit/0a9f9596a8bb6a78968cd484abac00b3af02e8f9

**Comment by noeppi-noeppi** [comment]
I used `3.2.11` as you also used that in your log

**Comment by lazynessmind** [comment]
works now. 🤔
