### ISSUE TITLE
Pair config value not editable ingame

### ISSUE THREAD

**Issue by MelanX** [ModdingX/LibX#82]
### Minecraft version

1.20.1

### LibX version

5.0.0

### Forge version

47.1.0

### The latest.log file

/

### Issue description

1. Create a config
2. Add a `Pair` to that config
3. Go in the ingame config editor
4. Try to edit the pair values

-> Text boxes can't be clicked, there is no blinking line in the box, and you can't write in the box.

**Comment by Gamemassa** [comment]
@MelanX ~~How did you get LibX version 5.0.0 for MC 1.20.1 ? I don't see it on Curseforge yet.~~ Never mind, I found it on Modrinth.

**Comment by MelanX** [comment]
If you use a launcher and download a mod which requires LibX, it will automatically download LibX. If you wanna download on website, use Modrinth (as you did), or here on CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/libx/files/all?filter-game-version=1738749986%3a75125
